#!/usr/bin/env python3
"""Inlines assets/ into a Java class for the TeaVM build.

The bundled .task and glider .txt files total a couple of hundred lines. Baking
them in keeps ModelEnv.openFile synchronous, which is what lets the
StreamTokenizer parsers cross to the browser unchanged - TeaVM cannot block on
fetch, so anything loaded at runtime would force the loaders to go async.

Usage: python3 web/tools/genassets.py [assetDir] [outFile]
"""
import io
import os
import sys

HEADER = '''package com.cloudwalk.web;

import com.cloudwalk.harness.AssetSource;

/**
 * The bundled data files, inlined at build time.
 *
 * Generated by web/tools/genassets.py from assets/ - do not edit by hand.
 * They total a couple of hundred lines, so inlining them keeps asset loading
 * synchronous, which is what lets the StreamTokenizer parsers stay untouched.
 */
public final class BakedAssets implements AssetSource {

'''


def ident(name):
    return name.replace('.', '_').replace('-', '_').upper()


def main():
    asset_dir = sys.argv[1] if len(sys.argv) > 1 else 'assets'
    out_file = sys.argv[2] if len(sys.argv) > 2 else \
        'web/src/main/java/com/cloudwalk/web/BakedAssets.java'

    names = sorted(n for n in os.listdir(asset_dir)
                   if os.path.isfile(os.path.join(asset_dir, n)))

    out = io.StringIO()
    out.write(HEADER)
    for n in names:
        with io.open(os.path.join(asset_dir, n), encoding='utf-8') as f:
            text = f.read()
        out.write('\tprivate static final String %s =\n' % ident(n))
        parts = ['\t\t\t"%s\\n"' % ln.replace('\\', '\\\\').replace('"', '\\"')
                 for ln in text.split('\n')]
        out.write(' +\n'.join(parts) + ';\n\n')

    out.write('\tpublic String read(String name) {\n')
    for n in names:
        out.write('\t\tif ("%s".equals(name)) {\n\t\t\treturn %s;\n\t\t}\n' % (n, ident(n)))
    out.write('\t\treturn null;\n\t}\n}\n')

    with io.open(out_file, 'w', encoding='utf-8') as f:
        f.write(out.getvalue())
    print('wrote %s (%d assets, %d bytes)' % (out_file, len(names), len(out.getvalue())))


if __name__ == '__main__':
    main()
