#!/usr/bin/env bash
#
# Typechecks the Android module without an Android SDK.
#
# CI and dev machines should just run ./gradlew :android:assembleDebug. This is
# for environments that have no SDK at all - it compiles the module against the
# API 16 stub jar published on Maven Central, plus hand-written stand-ins for
# the few things that jar lacks and for the R class AGP generates.
#
# It is a typecheck, not a build: it catches signature and wiring mistakes,
# which is most of what a refactor breaks. It cannot catch resource problems,
# and it reports a handful of known false positives from the stub jar being
# older than the project's minSdk 21:
#
#   TasksAdapter.java        XmlPullParser missing from the stub jar
#   ColorPickerView.java     obtainStyledAttributes(AttributeSet, int), API 21+
#   ColorPickerPreference    same
#
set -euo pipefail
cd "$(dirname "$0")/.."

CACHE="${TMPDIR:-/tmp}/fc-android-typecheck"
mkdir -p "$CACHE/stub"

# Maven Central rate-limits, and a throttled request still exits 0 with an
# HTML body - so check we actually got a zip, and retry if not.
fetch() {
  local url=$1 out=$2 tries=0
  while ! unzip -tq "$CACHE/$out" >/dev/null 2>&1; do
    tries=$((tries + 1))
    if [ $tries -gt 4 ]; then
      echo "could not download $url (rate limited?)" >&2
      exit 1
    fi
    [ $tries -eq 1 ] || sleep $((tries * 5))
    curl -sSL -o "$CACHE/$out" "$url"
  done
}

M=https://repo1.maven.org/maven2
fetch $M/com/google/android/android/4.1.1.4/android-4.1.1.4.jar android.jar
fetch $M/org/apache/httpcomponents/httpclient/4.5.14/httpclient-4.5.14.jar httpclient.jar
fetch $M/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar httpcore.jar
fetch $M/org/json/json/20240303/json-20240303.jar json.jar

mkdir -p "$CACHE/stub/javax/microedition/khronos/egl" "$CACHE/stub/javax/microedition/khronos/opengles"
cat > "$CACHE/stub/javax/microedition/khronos/egl/EGLConfig.java" <<'EOF'
package javax.microedition.khronos.egl;
public interface EGLConfig { }
EOF
cat > "$CACHE/stub/javax/microedition/khronos/opengles/GL.java" <<'EOF'
package javax.microedition.khronos.opengles;
public interface GL { }
EOF
cat > "$CACHE/stub/javax/microedition/khronos/opengles/GL10.java" <<'EOF'
package javax.microedition.khronos.opengles;
public interface GL10 extends GL { int GL_POLYGON_SMOOTH_HINT = 0x0C53; int GL_NICEST = 0x1102; }
EOF

# R is generated by AGP; synthesise one from whatever the sources reference.
python3 - "$CACHE/stub" <<'EOF'
import collections, io, os, re, sys
stub = sys.argv[1]
refs = collections.defaultdict(set)
for root, _, files in os.walk('android/src/main/java'):
    for f in files:
        if f.endswith('.java'):
            txt = io.open(os.path.join(root, f), encoding='utf-8', errors='ignore').read()
            for m in re.finditer(r'\bR\.(\w+)\.(\w+)\b', txt):
                refs[m.group(1)].add(m.group(2))
body = ['/** Stand-in for the R class AGP generates. Typecheck only. */', 'public final class R {']
for cat in sorted(refs):
    body.append('\tpublic static final class %s {' % cat)
    body += ['\t\tpublic static final int %s = 0;' % n for n in sorted(refs[cat])]
    body.append('\t}')
body.append('}')
for pkg in ('com.cloudwalk.flightclub', 'afzkl.development.colorpickerview'):
    d = os.path.join(stub, *pkg.split('.'))
    os.makedirs(d, exist_ok=True)
    io.open(os.path.join(d, 'R.java'), 'w').write('package %s;\n\n%s\n' % (pkg, '\n'.join(body)))
EOF

./gradlew -q :core:jar
CP="$CACHE/android.jar:$CACHE/httpclient.jar:$CACHE/httpcore.jar:$CACHE/json.jar:core/build/libs/core.jar"
javac -nowarn -source 8 -target 8 -Xlint:-options -cp "$CP" -d "$CACHE/out" \
  $(find android/src/main/java "$CACHE/stub" -name '*.java') 2>&1 | grep "error:" || true
